#spring.data.mongodb.uri=mongodb://10.213.65.204:27017
#spring.data.mongodb.database=study


spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration, org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    mongodb:
      host: mongo1
      port: 27017
      username: user3
      password: user3


mongodb:
  primary:
    host: mongo1
    port: 27017
    database: test1
    username: user1
    password: user1
    uri: mongodb://user1:user1@mongo1:27017,mongo2:27017,mongo3:27017/test1?replicaSet=abtest_set
  secondary:
    host: mongo2
    port: 27017
    database: test2
    username: user2
    password: user2
    uri: mongodb://user2:user2@mongo1:27017,mongo2:27017,mongo3:27017/test2?replicaSet=abtest_set
#  secondary:
#    host: localhost
#    port: 40000
#    database: reactive
#    username:
#    password:
#    uri: mongodb://localhost:40000/reactive


